services:
  forum:
    image: forum
    container_name: forumapi
    build:
      context: .
      dockerfile: src/Forum/Dockerfile
    ports:
      - "8000:8080"
      - "8443:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - forum_https:/https
    depends_on:
      forumdb:
        condition: service_healthy
      messagebroker:
        condition: service_healthy
    networks:
      - forum-network
    restart: unless-stopped

  notification:
    image: notification
    container_name: notificationapi
    build:
      context: .
      dockerfile: src/Notification/Dockerfile
    ports:
      - "8001:8080"
      - "8444:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - notification_https:/https
    depends_on:
      notificationdb:
        condition: service_healthy
      messagebroker:
        condition: service_healthy
    networks:
      - forum-network
    restart: unless-stopped

  user:
    image: user
    container_name: userapi
    build:
      context: .
      dockerfile: src/User/Dockerfile
    ports:
      - "8002:8080"
      - "8445:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - user_https:/https
    depends_on:
      userdb:
        condition: service_healthy
    networks:
      - forum-network
    restart: unless-stopped

  messagebroker:
    image: rabbitmq:management
    container_name: messagebroker
    hostname: forum-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - forum-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
  userdb:
    image: postgres
    container_name: userdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=UserDb
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_user:/var/lib/postgresql
    networks:
      - forum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  forumdb:
    image: postgres
    container_name: forumdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ForumDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_forum:/var/lib/postgresql
    networks:
      - forum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  notificationdb:
    image: postgres
    container_name: notificationdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NotificationDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_notification:/var/lib/postgresql
    networks:
      - forum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_user:
  postgres_forum:
  postgres_notification:
  forum_https:
  notification_https:
  user_https:
networks:
  forum-network:
    driver: bridge
  

